### PR TITLE
Merge fix for #26

### PR DESCRIPTION
**Pull request by RedFantom**
The commits made to the branch `Zarainia-patch-1` should fix issue #26. Review is required before merging to ensure everything is still working correctly.

### CODE REVIEW

**Comment by RedFantom** [comment]
Oh, that's a good one indeed! Remember, you can reference issues and pull requests by using their number preceded by a hashtag: #29 and #26.

**Comment by Zarainia** [comment]
Right, I'm new to this Github thing.

**Comment by RedFantom** [comment]
Nice job @Zarainia! I will now delete your `patch-1` branch.

**Comment by RedFantom** [comment]
Sorry about that, that should've been #30 instead.

**Pull request merged**
